name: Publish Rasa Docker image
on:
  [push]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - 
        name: Build with Maven
        run: mvn clean install --file chatbot/pom.xml
      -
        name: Build & push Rasa Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cl13ntl3ss/rasa_container
          tags: latest
          registry: docker.io
          dockerfile: rasa_container/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build & push Backend Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cl13ntl3ss/chatbotapp
          tags: latest
          registry: docker.io
          dockerfile: chatbot/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
