name: Publish Rasa Docker image
on:
  [push]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cl13ntl3ss/chatbotapp
          tags: latest
          registry: docker.io
          dockerfile: rasa_container/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
