name: Publish Frontend Docker Image to DockerHub
on:
  push:
    branches:
    - main
    paths:
    - AngularFrontend
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - 
        name: Build with Maven
        run: mvn clean install --file chatbot/pom.xml
      -
        name: Build & push Frontend Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: AngularFrontend/chatFE
          image: cl13ntl3ss/chatbotfrontend
          tags: latest
          registry: docker.io
          dockerfile: AngularFrontend/chatFE/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
